sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  slack: vehicle-history:SKcpyDevstQaov9UMzwuns12
  email: true
node_js:
  - '5'
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test-travis
after_success:
  - npm install coveralls@2.11.2 && cat ./coverage/lcov.info | coveralls"
env:
  - NODE_ENV=test CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8